import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavigationMenuDemo from "@/components/MainNav/Navbar";
import { Toaster } from "@/components/ui/sonner"
import { StoreProvider } from "@/store/StoreProvider";
import { SessionProvider } from "next-auth/react";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
<html lang="en">
      <body className={inter.className}>
      <SessionProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <NavigationMenuDemo />
          <Toaster />
          {children}
        </ThemeProvider>
        </SessionProvider>
      </body>
    </html> 
    </StoreProvider>
    
  );
}
